steps:
  - name: Update system
    plugin: Script
    script:
      - gem uninstall bundler
      - apt-get update
  - name: Install Imagemagick
    plugin: Script
    script:
      - apt-get install -y software-properties-common imagemagick
      - apt-add-repository -y ppa:brightbox/ruby-ng
      - apt-get update
  - name: Install Ruby 2.2
    plugin: Script
    script:
      - apt-get install -y ruby2.2 ruby2.2-dev
      - update-alternatives --config ruby
      - gem install bundler -v 1.7.9
  - name: Install Jekyll Dependencies
    plugin: Script
    script:
      - cd $SRC_DIR
      - bundle install --path vendor/bundle
  - name: Build Jekyll site
    plugin: Script
    script:
      - locale-gen en_US.UTF-8
      - LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 bundle exec jekyll build --destination=/var/www/html
  - name: Upgrade to php 7
    plugin: Script
    script: |
      apt-get update
      apt-get install -y software-properties-common language-pack-en-base
      LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php
      LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/apache2
      apt-get update
      apt-get install -y php7.0 libapache2-mod-php7.0 php7.0-gd php7.0-curl php7.0-json php7.0-mbstring php7.0-mysql php7.0-mcrypt php7.0-imagick php7.0-dev php7.0-gmp php7.0-xml
      php -v
      apachectl graceful
