image: proboci/ubuntu:20.04-php7.4-mysql5.7
steps:

  - name: Install Imagemagick and Ruby
    plugin: Script
    script:
      - apt-get update
      - apt-get install -y software-properties-common imagemagick ruby-full \

  - name: Install Bundler
    plugin: Script
    script:
      - gem install bundler -v 2.1.4

  - name: Install Jekyll Dependencies
    plugin: Script
    script:
      - cd $SRC_DIR
      - bundle config set --local path 'vendor/bundle'
      - bundle install
      - bundle update jekyll

  - name: Build Jekyll site
    plugin: Script
    script:
      - locale-gen en_US.UTF-8
      - LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 bundle exec jekyll build --destination=/var/www/html
